namespace StarMapRebalanced
{
    using System.Collections.Generic;


    internal class StarmapDict
    {
        public static Dictionary<string, Dictionary<SimHashes, float>> harvestablePOIs = new Dictionary<string, Dictionary<SimHashes, float>>() { };

        public static void initialize()
        {
            harvestablePOIs["REMOVE_CarbonAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.RefinedCarbon,
                    3f
                },
                {
                    SimHashes.Carbon,
                    12f
                },
                {
                    SimHashes.Diamond,
                    5f
                }
            };
            harvestablePOIs["REMOVE_MetallicAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                 {
                    SimHashes.MoltenIron,
                    3f
                 },
                 {
                    SimHashes.Copper,
                    3f
                 },
                 {
                    SimHashes.Steel,
                    3f
                 },
                 {
                    SimHashes.IgneousRock,
                    1f
                 }
            };
            harvestablePOIs["REMOVE_SatelliteField"] = new Dictionary<SimHashes, float>()
            {
                  {
                    SimHashes.Steel,
                    3f
                  },
                  {
                    SimHashes.Copper,
                    3f
                  },
                  {
                    SimHashes.Glass,
                    3f
                  },
                  {
                    SimHashes.Ceramic,
                    1f
                  }
            };
            harvestablePOIs["REMOVE_RockyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                  SimHashes.Fossil,
                  3f
                },
                {
                  SimHashes.MaficRock,
                  3f
                },
                {
                  SimHashes.Obsidian,
                  2f
                },
                {
                  SimHashes.Granite,
                  1f
                },
                {
                  SimHashes.Regolith,
                  1f
                }
            };
            harvestablePOIs["REMOVE_InterstellarIceField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                2.5f
              },
              {
                SimHashes.DirtyIce,
                4f
              },
              {
                SimHashes.Granite,
                3f
              },
              {
                SimHashes.LiquidOxygen,
                0.5f
              }
            };
            harvestablePOIs["REMOVE_OrganicMassField"] = new Dictionary<SimHashes, float>()
            {
              {
                  SimHashes.SlimeMold,
                  4f
              },
              {
                  SimHashes.SedimentaryRock,
                  4f
              },
              {
                  SimHashes.Fertilizer,
                  2f
              }

            };
            harvestablePOIs["REMOVE_IceAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                6f
              },
              {
                SimHashes.Wolframite,
                2f
              },
              {
                SimHashes.SolidOxygen,
                1.5f
              },
              {
                SimHashes.LiquidMethane,
                0.5f
              }
            };
            harvestablePOIs["REMOVE_GasGiantCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Methane,
                1f
              },
              {
                SimHashes.LiquidMethane,
                4f
              },
              {
                SimHashes.SolidMethane,
                4f
              },
              {
                SimHashes.Hydrogen,
                1f
              }
            };
            harvestablePOIs["REMOVE_ChlorineCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Chlorine,
                2.5f
              },
              {
                SimHashes.BleachStone,
                7.5f
              }
            };
            harvestablePOIs["REMOVE_GildedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Gold,
                5f
              },
              {
                SimHashes.MaficRock,
                3f
              },
              {
                SimHashes.Fullerene,
                1f
              },
              {
                SimHashes.Regolith,
                1f
              }
            };
            harvestablePOIs["GlimmeringAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Wolframite,
                6f
              },
              {
                SimHashes.MoltenTungsten,
                2f
              },
              {
                SimHashes.Carbon,
                1f
              },
              {
                SimHashes.Katairite,
                1f
              }
            };
            harvestablePOIs["REMOVE_HeliumCloud"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.Hydrogen,
                    4f
                },
                {
                    SimHashes.Lime,
                    1f
                },
                {
                    SimHashes.Water,
                    5f
                }
            };
            harvestablePOIs["REMOVE_OilyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SolidPetroleum,
                7f
              },
              {
                SimHashes.CrudeOil,
                2f
              },
              {
                SimHashes.SolidMethane,
                1f
              }
            };
            harvestablePOIs["REMOVE_OxidizedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Rust,
                6f
              },
              {
                SimHashes.OxyRock,
                4f
              }
            };
            harvestablePOIs["REMOVE_SaltyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Salt,
                5f
              },
              {
                SimHashes.Fossil,
                4f
              },
              {
                SimHashes.BleachStone,
                1f
              },
              {
                SimHashes.Granite,
                3f
              }
            };
            harvestablePOIs["FrozenOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                3f
              },
              {
                SimHashes.Ice,
                2f
              },
              {
                SimHashes.Cuprite,
                1f
              },
              {
                SimHashes.IronOre,
                1f
              },
              {
                SimHashes.GoldAmalgam,
                1f
              },
              {
                SimHashes.AluminumOre,
                1f
              },
              {
                SimHashes.Cobaltite,
                1f
              }
            };
            harvestablePOIs["REMOVE_ForestyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                4f
              },
              {
                SimHashes.Dirt,
                2f
              },
              {
                SimHashes.AluminumOre,
                2f
              }
            };
            harvestablePOIs["REMOVE_SwampyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SedimentaryRock,
                2f
              },
              {
                SimHashes.ToxicMud,
                6f
              },
              {
                SimHashes.Cobaltite,
                2f
              }
            };
            harvestablePOIs["REMOVE_SandyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SandStone,
                4f
              },
              {
                SimHashes.Algae,
                2f
              },
              {
                SimHashes.Cuprite,
                2f
              },
              {
                SimHashes.Sand,
                2f
              }
            };
            harvestablePOIs["REMOVE_RadioactiveGasCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                1f
              },
              {
                SimHashes.Fallout,
                4.5f
              },
              {
                SimHashes.ChlorineGas,
                4.5f
              }
            };
            harvestablePOIs["RadioactiveAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                2f
              },
              {
                SimHashes.BleachStone,
                2f
              },
              {
                SimHashes.Sulfur,
                2.5f
              },
              {
                SimHashes.Rust,
                2.5f
              },
              {
                SimHashes.Lead,
                1f
              }
            };
            harvestablePOIs["REMOVE_OxygenRichAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.OxyRock,
                4f
              },
              {
                SimHashes.SolidOxygen,
                3f
              },
              {
                SimHashes.ContaminatedOxygen,
                2f
              },
              {
                SimHashes.LiquidOxygen,
                1f
              }
            };
            harvestablePOIs["REMOVE_InterstellarOcean"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SaltWater,
                2.5f
              },
              {
                SimHashes.Brine,
                2.5f
              },
              {
                SimHashes.Salt,
                2.5f
              },
              {
                SimHashes.BrineIce,
                2.5f
              }
            };
        }
    }
}
