namespace StarMapRebalanced
{
    using System.Collections.Generic;

    //this is where you make changes
    internal class StarmapDict
    {
        public static Dictionary<string, Dictionary<SimHashes, float>> harvestablePOIs = new Dictionary<string, Dictionary<SimHashes, float>>() { };

        public static void initialize()
        {
            harvestablePOIs["CarbonAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.RefinedCarbon,
                    3f
                },
                {
                    SimHashes.Carbon,
                    12f
                },
                {
                    SimHashes.Diamond,
                    5f
                }
            };
            harvestablePOIs["MetallicAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                 {
                    SimHashes.Iron,
                    3f
                 },
                 {
                    SimHashes.Copper,
                    3f
                 },
                 {
                    SimHashes.Steel,
                    3f
                 },
                 {
                    SimHashes.IgneousRock,
                    1f
                 }
            };
            harvestablePOIs["SatelliteField"] = new Dictionary<SimHashes, float>()
            {
                  {
                    SimHashes.Steel,
                    3f
                  },
                  {
                    SimHashes.Copper,
                    3f
                  },
                  {
                    SimHashes.Glass,
                    3f
                  },
                  {
                    SimHashes.Ceramic,
                    1f
                  }
            };
            harvestablePOIs["RockyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                  SimHashes.Fossil,
                  3f
                },
                {
                  SimHashes.MaficRock,
                  3f
                },
                {
                  SimHashes.Obsidian,
                  2f
                },
                {
                  SimHashes.Granite,
                  1f
                },
                {
                  SimHashes.Regolith,
                  1f
                }
            };
            harvestablePOIs["InterstellarIceField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                2.5f
              },
              {
                SimHashes.DirtyIce,
                4f
              },
              {
                SimHashes.Granite,
                3f
              },
              {
                SimHashes.SolidOxygen,
                0.5f
              }
            };
            harvestablePOIs["OrganicMassField"] = new Dictionary<SimHashes, float>()
            {
              {
                  SimHashes.SlimeMold,
                  4f
              },
              {
                  SimHashes.SedimentaryRock,
                  3f
              },
              {
                  SimHashes.Fertilizer,
                  2f
              },
              {
                  SimHashes.Resin,
                  1f
              }

            };
            harvestablePOIs["IceAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                6f
              },
              {
                SimHashes.Wolframite,
                2f
              },
              {
                SimHashes.SolidOxygen,
                1.5f
              },
              {
                SimHashes.SolidMethane,
                0.5f
              }
            };
            harvestablePOIs["GasGiantCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Methane,
                1f
              },
              {
                SimHashes.LiquidMethane,
                4f
              },
              {
                SimHashes.SolidMethane,
                4f
              },
              {
                SimHashes.Hydrogen,
                1f
              }
            };
            harvestablePOIs["ChlorineCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Chlorine,
                2.5f
              },
              {
                SimHashes.BleachStone,
                7.5f
              }
            };
            harvestablePOIs["GildedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Gold,
                5f
              },
              {
                SimHashes.FoolsGold,
                3f
              },
              {
                SimHashes.Fullerene,
                1f
              },
              {
                SimHashes.Regolith,
                1f
              }
            };
            harvestablePOIs["GlimmeringAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Wolframite,
                6f
              },
              {
                SimHashes.Tungsten,
                3f
              },
              {
                SimHashes.Katairite,
                1f
              }
            };
            harvestablePOIs["HeliumCloud"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.Ethanol,
                    3f
                },
                {
                    SimHashes.Graphite,
                    1f
                },
                {
                    SimHashes.Lime,
                    1f
                },
                {
                    SimHashes.Water,
                    5f
                }
            };
            harvestablePOIs["OilyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SolidPetroleum,
                7f
              },
              {
                SimHashes.CrudeOil,
                1.5f
              },
              {
                SimHashes.SolidMethane,
                1f
              },
              {
                SimHashes.Isoresin,
                0.5f
              }
            };
            harvestablePOIs["OxidizedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Rust,
                8f
              },
              {
                SimHashes.OxyRock,
                2f
              }
            };
            harvestablePOIs["SaltyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Salt,
                5f
              },
              {
                SimHashes.Fossil,
                4f
              },
              {
                SimHashes.BleachStone,
                1f
              }
            };
            harvestablePOIs["FrozenOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                3f
              },
              {
                SimHashes.Ice,
                2f
              },
              {
                SimHashes.Cuprite,
                1f
              },
              {
                SimHashes.IronOre,
                1f
              },
              {
                SimHashes.GoldAmalgam,
                1f
              },
              {
                SimHashes.AluminumOre,
                1f
              },
              {
                SimHashes.Cobaltite,
                1f
              }
            };
            harvestablePOIs["ForestyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                4f
              },
              {
                SimHashes.Dirt,
                2f
              },
              {
                SimHashes.Resin,
                2f
              },
              {
                SimHashes.AluminumOre,
                2f
              }
            };
            harvestablePOIs["SwampyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Mud,
                2f
              },
              {
                SimHashes.ToxicSand,
                6f
              },
              {
                SimHashes.Cobaltite,
                2f
              }
            };
            harvestablePOIs["SandyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SandStone,
                4f
              },
              {
                SimHashes.Algae,
                2f
              },
              {
                SimHashes.Cuprite,
                1f
              },
              {
                SimHashes.Sand,
                3f
              }
            };
            harvestablePOIs["RadioactiveGasCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                4f
              },
              {
                SimHashes.Fallout,
                2f
              },
              {
                SimHashes.ChlorineGas,
                2f
              }
            };
            harvestablePOIs["RadioactiveAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                2f
              },
              {
                SimHashes.Sulfur,
                2f
              },
              {
                SimHashes.Wolframite,
                2f
              },
              {
                SimHashes.Lead,
                2f
              }
            };
            harvestablePOIs["OxygenRichAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.OxyRock,
                4f
              },
              {
                SimHashes.SolidOxygen,
                3f
              },
              {
                SimHashes.ContaminatedOxygen,
                2f
              },
              {
                SimHashes.LiquidOxygen,
                1f
              }
            };
            harvestablePOIs["InterstellarOcean"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SaltWater,
                2.5f
              },
              {
                SimHashes.Brine,
                2.5f
              },
              {
                SimHashes.Salt,
                2.5f
              },
              {
                SimHashes.BrineIce,
                2.5f
              }
            };
        }
    }
}
