namespace StarMapRebalanced
{
    using System.Collections.Generic;


    internal class StarmapDict
    {
        public static Dictionary<string, Dictionary<SimHashes, float>> harvestablePOIs = new Dictionary<string, Dictionary<SimHashes, float>>() { };

        public static void initialize()
        {
            harvestablePOIs["CarbonAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.RefinedCarbon,
                    2f
                },
                {
                    SimHashes.Carbon,
                    8f
                }
            };
            harvestablePOIs["MetallicAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                 {
                    SimHashes.MoltenIron,
                    1.25f
                 },
                 {
                    SimHashes.Cuprite,
                    1.75f
                 },
                 {
                    SimHashes.Steel,
                    1f
                 },
                 {
                    SimHashes.Obsidian,
                    6f
                 }
            };
            harvestablePOIs["SatelliteField"] = new Dictionary<SimHashes, float>()
            {
                  {
                    SimHashes.Steel,
                    0.5f
                  },
                  {
                    SimHashes.IronOre,
                    3f
                  },
                  {
                    SimHashes.MoltenCopper,
                    2.5f
                  },
                  {
                    SimHashes.Glass,
                    1f
                  },
                  {
                    SimHashes.Ceramic,
                    3f
                  }
            };
            harvestablePOIs["RockyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
                {
                  SimHashes.Fossil,
                  1f
                },
                {
                  SimHashes.SedimentaryRock,
                  2f
                },
                {
                  SimHashes.MaficRock,
                  3f
                },
                {
                  SimHashes.Obsidian,
                  2f
                },
                {
                  SimHashes.Granite,
                  1f
                },
                {
                  SimHashes.Regolith,
                  1f
                }
            };
            harvestablePOIs["InterstellarIceField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                2.5f
              },
              {
                SimHashes.DirtyIce,
                4f
              },
              {
                SimHashes.Granite,
                3f
              },
              {
                SimHashes.LiquidOxygen,
                0.5f
              }
            };
            harvestablePOIs["OrganicMassField"] = new Dictionary<SimHashes, float>()
            {
              {
                  SimHashes.SlimeMold,
                  4f
              },
              {
                  SimHashes.Algae,
                  3f
              },
              {
                  SimHashes.ContaminatedOxygen,
                  2f
              },
              {
                  SimHashes.Fertilizer,
                  1f
              }

            };
            harvestablePOIs["IceAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Ice,
                6f
              },
              {
                SimHashes.LiquidCarbonDioxide,
                2f
              },
              {
                SimHashes.SolidOxygen,
                1.5f
              },
              {
                SimHashes.LiquidMethane,
                0.5f
              }
            };
            harvestablePOIs["GasGiantCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Methane,
                1f
              },
              {
                SimHashes.LiquidMethane,
                4f
              },
              {
                SimHashes.SolidMethane,
                2f
              },
              {
                SimHashes.LiquidHydrogen,
                3f
              }
            };
            harvestablePOIs["ChlorineCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Chlorine,
                2.5f
              },
              {
                SimHashes.BleachStone,
                7.5f
              }
            };
            harvestablePOIs["GildedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Gold,
                5f
              },
              {
                SimHashes.RefinedCarbon,
                3f
              },
              {
                SimHashes.Fullerene,
                1f
              },
              {
                SimHashes.Regolith,
                1f
              }
            };
            harvestablePOIs["GlimmeringAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Wolframite,
                6f
              },
              {
                SimHashes.MoltenTungsten,
                2f
              },
              {
                SimHashes.CarbonDioxide,
                1f
              },
              {
                SimHashes.Katairite,
                1f
              }
            };
            harvestablePOIs["HeliumCloud"] = new Dictionary<SimHashes, float>()
            {
                {
                    SimHashes.Hydrogen,
                    2f
                },
                {
                    SimHashes.Lime,
                    0.5f
                },
                {
                    SimHashes.Water,
                    7.5f
                }
            };
            harvestablePOIs["OilyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SolidPetroleum,
                7f
              },
              {
                SimHashes.CrudeOil,
                1.9f
              },
              {
                SimHashes.SolidMethane,
                1f
              },
              {
                SimHashes.Isoresin,
                0.1f
              }
            };
            harvestablePOIs["OxidizedAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Rust,
                8f
              },
              {
                SimHashes.OxyRock,
                2f
              }
            };
            harvestablePOIs["SaltyAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Salt,
                3f
              },
              {
                SimHashes.Fossil,
                2f
              },
              {
                SimHashes.SaltWater,
                3f
              },
              {
                SimHashes.Granite,
                2f
              }
            };
            harvestablePOIs["FrozenOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                4.5f
              },
              {
                SimHashes.Ice,
                3f
              },
              {
                SimHashes.Cuprite,
                0.5f
              },
              {
                SimHashes.IronOre,
                0.5f
              },
              {
                SimHashes.GoldAmalgam,
                0.5f
              },
              {
                SimHashes.AluminumOre,
                0.5f
              },
              {
                SimHashes.Cobaltite,
                0.5f
              }
            };
            harvestablePOIs["ForestyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.IgneousRock,
                4f
              },
              {
                SimHashes.Dirt,
                4f
              },
              {
                SimHashes.AluminumOre,
                1f
              },
              {
                SimHashes.Resin,
                1f
              }
            };
            harvestablePOIs["SwampyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.Mud,
                3f
              },
              {
                SimHashes.ToxicMud,
                6f
              },
              {
                SimHashes.Cobaltite,
                1f
              }
            };
            harvestablePOIs["SandyOreField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SandStone,
                4f
              },
              {
                SimHashes.Algae,
                2f
              },
              {
                SimHashes.Cuprite,
                1f
              },
              {
                SimHashes.Sand,
                3f
              }
            };
            harvestablePOIs["RadioactiveGasCloud"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                2f
              },
              {
                SimHashes.Fallout,
                4f
              },
              {
                SimHashes.ChlorineGas,
                4f
              }
            };
            harvestablePOIs["RadioactiveAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.UraniumOre,
                1f
              },
              {
                SimHashes.BleachStone,
                2.5f
              },
              {
                SimHashes.Sulfur,
                2.5f
              },
              {
                SimHashes.Rust,
                2.5f
              },
              {
                SimHashes.Lead,
                1.5f
              }
            };
            harvestablePOIs["OxygenRichAsteroidField"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.OxyRock,
                4f
              },
              {
                SimHashes.SolidOxygen,
                3f
              },
              {
                SimHashes.ContaminatedOxygen,
                2f
              },
              {
                SimHashes.LiquidOxygen,
                1f
              }
            };
            harvestablePOIs["InterstellarOcean"] = new Dictionary<SimHashes, float>()
            {
              {
                SimHashes.SaltWater,
                2.5f
              },
              {
                SimHashes.Brine,
                2.5f
              },
              {
                SimHashes.BleachStone,
                2.5f
              },
              {
                SimHashes.BrineIce,
                2.5f
              }
            };
        }
    }
}
